### ISSUE TITLE
Socket.io "Add Request" shows white screen and socket disconnection

### ISSUE THREAD

**Issue by ctfrancia** [FirecampLab/fc-support#15]
Hi, when trying to "add request" on the left hand side from any part of extension, the screen goes white and when inspecting the dev tools I see:
>"[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312" 

and 

>"fcapp.bundle.js:83 TypeError: Cannot read property 'type' of undefined
at new t (fcapp.bundle.js:218)
at lo (fcapp.bundle.js:83)"

**Comment by Nishchit14** [comment]
Thank you for sharing the issue.  It has been fixed and you can ass request now from left-side project panel. :)

resolved in v0.2.9, if still, you're facing any issue feel free to open this issue again.
