### ISSUE TITLE
Is in a connecting state even after a failed handshake with the server.

### ISSUE THREAD

**Issue by priyank6796** [FirecampLab/fc-support#2]
When the tool fails to connect with the socket.io server because of some socket.io server issue. the tool is in a connecting state even after a failed handshake with the server. the tool should display the error message to the user after a failed handshake with the server. Currently, I can find error messages in the chrome developer console. basically, it should have a connection timeout mechanism.

**Comment by Nishchit14** [comment]
@priyank6796 thanks for filing the issue. :fire: :tent: 

This bug has been solved in `v0.0.16`. you can test it with Firecamp now.
