### ISSUE TITLE
bug: wrong cursor location after entering an open bracket JSON

### ISSUE THREAD

**Issue by ctfrancia** [FirecampLab/fc-support#21]
There appears to have a small bug. While putting in the argument for an emit (in socket io) after you place the opening blacket( { ) and then after you press enter, the closing bracket is entered.(which is fine) however the cursor location is completely wrong and navigating to correct anything is a nightmare!

**Comment by Nishchit14** [comment]
Thanks @ctfrancia for filing this bug, 

This has been resolved in v.0.4.3
