### ISSUE TITLE
Add socket.io namespace options

### ISSUE THREAD

**Issue by delronkung** [FirecampLab/fc-support#5]
It would be nice if we could specify socket.io namespace.

**Comment by Nishchit14** [comment]
@delronkung you can add directly add the namespace in the URL itself


Here `myNamespace` in the URL is a custom namespace, please test it at your side and still facing the issue feel free to extend this thread :)

![image](https://user-images.githubusercontent.com/5078921/50634554-11754880-0f75-11e9-8878-e2b4cbfbaa9c.png)

**Comment by Nishchit14** [comment]
@delronkung I am closing this issue, If you still think that It would have some improvement then feel free to re-open it.
